### ISSUE TITLE
Inverter

### ISSUE THREAD

**Issue by Weltkugel** [jurjanbrust/esp8266_vfd#8]
Hi,

no issue, but another inverter-solution: you can invert the ESP-serial-signal with software. There is no need for an hardware-inverter.

Serial.begin(19200, SERIAL_8N1, SERIAL_FULL, 1, true); // true = invert

**Comment by jurjanbrust** [comment]
Thanks! I will test this for sure. 
Added comments to the readme.md for now. 
Do you have a VFD?

**Comment by Weltkugel** [comment]
I love VFDs, so I always have a look on other VFD-github-projects. Your pictures are great. Yes, I have some Noritake, Futaba and  of course the IEE 03602-122-09220. I'm the guy who draw the Fritzing-raspberrypi+transistor scheme in the readme.md ;-)
Last days I connected a HD44780 with (inverted) serial to an ESP (https://www.mouser.de/datasheet/2/127/die_sere-329.pdf) and found the software-solution here: https://github.com/esp8266/Arduino/issues/4896#issuecomment-1248517534 and it works.
My current target is to show infos from MusicPlayerDaemon via ESP8266.

**Comment by jurjanbrust** [comment]
Yes. I also love VFD's! Would love to get another IEE 03602-122-09220. Bought mine in 2002 (11 years ago!) for 37 euro.  No way to get one for that price nowadays sadly,  If you know any VFDs from IEE that are on sale, let me know. I even visited the factory in Los Angeles, but they sell by the 1000, which is a bit too much for me ;)
Hope you don't mind me using the Fritzing.. :) I can remove it if you want.
Nice idea to add show MusicPlayerDaemon playlists.  I wanted to add Spotify, but never got to it.

**Comment by Weltkugel** [comment]
I have never bought a VFD. I "found" them in used old electronic devices, like industrial scales or medical devices. The IEE 03602-122-09220 is the beautiest. The biggest is a 20x4 Noritake (double size of the IEE), but it has some weak pixel. The look of VFD reminds me to the  late 70s. It is art ;-) I'm fine with the use of that Fritzing-image. It was funny to discover, because I began to read the function of the schematics and did not see it at the first view :-) I will let you know, if there are IEE on sale in Germany. This is my [MoOde-Audio](https://github.com/moode-player/moode)- installation and because I want a ESP-LCD-Client in another room I stumble through github ;-)
![IMG_20170218_175422](https://user-images.githubusercontent.com/36031699/218334898-7835bc21-5165-4ff1-b9f7-1c8bd1fa8443.jpg)
